name: flutter_headset_listener
description: Used to monitor the connection or disconnection of Bluetooth headphones and wired headphones.
version: 0.0.1
homepage: https://github.com/coderghl/flutter_headset_listener

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_headset_listener
        pluginClass: FlutterHeadsetListenerPlugin
      ios:
        pluginClass: FlutterHeadsetListenerPlugin